Http:
  Listen: "127.0.0.1:10801"
Network: "testnet"
RemoteBootstrap: "https://glacier-labs.github.io/node-bootstrap/"
Keystore:
  PrivateKey: "dac6a8be09146d0915f4f4f14dd4b0b5f42fab8252d391793c26df6ec611671b"
TEE:
  IpfsURL: "https://greenfield.onebitdev.com/ipfs/"
